import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Button } from 'antd';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gestão de Chamados de Suporte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Gestão de Chamados de Suporte</h1>
      </header>
      <main className={styles.main}>
        <Button type="primary">Criar um Chamado</Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/eberjoe"
          target="_blank"
          rel="noopener noreferrer"
        >
          Engineered by Myself
        </a>
      </footer>
    </div>
  );
}
